export const emperorWeights = {
  Augustus: {
    'Visionary and powerful': 3,
    'Innovative and strategic': 3,
    'foresight and planning': 3,
    'Woody Spicy': 3,
    'Commanding and sophisticated': 3,
    'Sandalwood or Cedar': 3,
    'Vision and legacy': 3,
    'As a powerful and visionary leader': 3,
    Augustus: 3,
    'Founding a lasting empire': 3,
    'Commanding and inspiring respect': 3,
  },
  Trajan: {
    'Courageous and fearless': 3,
    'Bold and decisive': 3,
    'bravery and strength': 3,
    'Citrus Fresh': 3,
    'Invigorating and fresh': 3,
    'Bergamot or Lemon': 3,
    'Courage and honor': 3,
    'As a brave and fearless hero': 3,
    Trajan: 3,
    'Expanding the empire’s boundaries': 3,
    'Invigorating and energizing': 3,
  },
  'Marcus Aurelius': {
    'Diplomatic and wise': 3,
    'Diplomatic and fair': 3,
    'negotiation and wisdom': 3,
    'Aromatic Herbal': 3,
    'Calm and reflective': 3,
    'Lavender or Sage': 3,
    'Wisdom and diplomacy': 3,
    'As a wise and fair diplomat': 3,
    'Marcus Aurelius': 3,
    'Upholding peace and wisdom': 3,
    'Calming and wise': 3,
  },
  Constantine: {
    'Stoic and disciplined': 3,
    'Pragmatic and disciplined': 3,
    'patience and discipline': 3,
    Leather: 9,
    'Intense and bold': 3,
    'Leather or Tobacco': 3,
    'Discipline and order': 3,
    'As a disciplined and stoic figure': 3,
    Constantine: 3,
    'Reforming and strengthening the state': 3,
    'Intense and memorable': 3,
  },
  Nero: {
    'Passionate and ambitious': 3,
    'Charismatic and inspiring': 3,
    'passion and energy': 3,
    Oriental: 3,
    'Rich and complex': 3,
    'Amber or Vanilla': 3,
    'Passion and ambition': 3,
    'As a passionate and inspiring ruler': 3,
    Nero: 3,
    'Expressing creativity and passion': 3,
    'Rich and intriguing': 3,
  },
};

export const questions = [
  {
    question: 'How would you describe your personality?',
    answers: [
      'Visionary and powerful',
      'Courageous and fearless',
      'Diplomatic and wise',
      'Stoic and disciplined',
      'Passionate and ambitious',
    ],
  },
  {
    question: 'What’s your approach to leadership?',
    answers: [
      'Innovative and strategic',
      'Bold and decisive',
      'Diplomatic and fair',
      'Pragmatic and disciplined',
      'Charismatic and inspiring',
    ],
  },
  {
    question: 'How do you approach challenges?',
    answers: [
      'foresight and planning',
      'bravery and strength',
      'negotiation and wisdom',
      'patience and discipline',
      'passion and energy',
    ],
  },
  {
    question: 'Which type of fragrance do you usually gravitate toward?',
    answers: [
      'Woody Spicy',
      'Citrus Fresh',
      'Aromatic Herbal',
      'Leather',
      'Oriental',
    ],
  },
  {
    question: 'Do you prefer your scent to be:',
    answers: [
      'Commanding and sophisticated',
      'Invigorating and fresh',
      'Calm and reflective',
      'Intense and bold',
      'Rich and complex',
    ],
  },
  {
    question: 'Which scent note appeals to you the most?',
    answers: [
      'Sandalwood or Cedar',
      'Bergamot or Lemon',
      'Lavender or Sage',
      'Leather or Tobacco',
      'Amber or Vanilla',
    ],
  },
  {
    question: 'What do you value most in life?',
    answers: [
      'Vision and legacy',
      'Courage and honor',
      'Wisdom and diplomacy',
      'Discipline and order',
      'Passion and ambition',
    ],
  },
  {
    question: 'How do you want others to perceive you?',
    answers: [
      'As a powerful and visionary leader',
      'As a brave and fearless hero',
      'As a wise and fair diplomat',
      'As a disciplined and stoic figure',
      'As a passionate and inspiring ruler',
    ],
  },
  {
    question: 'Which of these historical figures intrigues you the most?',
    answers: ['Augustus', 'Trajan', 'Marcus Aurelius', 'Constantine', 'Nero'],
  },
  {
    question:
      'If you could embody one aspect of an emperor’s legacy, which would it be?',
    answers: [
      'Founding a lasting empire',
      'Expanding the empire’s boundaries',
      'Upholding peace and wisdom',
      'Reforming and strengthening the state',
      'Expressing creativity and passion',
    ],
  },
  {
    question: 'How would you like your fragrance to affect others?',
    answers: [
      'Commanding and inspiring respect',
      'Invigorating and energizing',
      'Calming and wise',
      'Intense and memorable',
      'Rich and intriguing',
    ],
  },
];
